name: cache-test # <-- put your slug here

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: (./bots/$GITHUB_WORKFLOW"/node_modules)
          key: (node-modules-${{ hashFiles('./bots/"$GITHUB_WORKFLOW"/package-lock.json') }})
          
      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: (cd ./bots/"$GITHUB_WORKFLOW" && npm install)

      - name: Process data
        run: (cd ./bots/"$GITHUB_WORKFLOW" && node index.js) 
